### ISSUE TITLE
Recognized value not updated after a hand disappears

### ISSUE THREAD

**Issue by 130s** [ros-drivers/leap_motion#11]
While `sender.py` no longer says any hand is detected, rostopic still returns hands value. Assuming sender.py works closer to SDK, this is likely a bug in ROS package?

```
rosrun leap_motion sender.py
:
Frame id: 60144, timestamp: 4703437196, hands: 0, fingers: 0, tools: 0, gestures: 0
Frame id: 60145, timestamp: 4703471920, hands: 0, fingers: 0, tools: 0, gestures: 0
```

```
rostopic echo /leapmotion/data 
:
header: 
  seq: 70228
  stamp: 
    secs: 0
    nsecs: 0
  frame_id: ''
direction: 
  x: 0.920395553112
  y: 0.1912419945
  z: -0.341025710106
normal: 
  x: 0.266604751348
  y: -0.944969654083
  z: 0.189616009593
palmpos: 
  x: 47.4868392944
  y: 46.736366272
  z: 18.5409545898
ypr: 
  x: 125.421399155
  y: 29.2830430497
  z: 101.73803212

---
```
